#Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4G"
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#Compose
org.gradle.unsafe.configuration-cache=true

#Hellogin
isSnapshot=false

hellogin-core="1.1.0
hellogin-core-network="1.1.0
hellogin-core-ui="1.1.0
hellogin-google="1.1.0
hellogin-github="1.1.0
hellogin-apple="1.1.0
hellogin-google-ui="1.1.0
hellogin-github-ui="1.1.0
hellogin-apple-ui="1.1.0